"""create booking core tables

Revision ID: 9abb6dc82f89
Revises:
Create Date: 2026-10-10 15:11:09.181964+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9abb6dc82f89"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "booking_slots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "service",
            sa.Enum("lunch", "dinner", name="service", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("service IN ('lunch', 'dinner')", name=op.f("ck_booking_slots_service")),
        sa.CheckConstraint("end_time > start_time", name=op.f("ck_booking_slots_time_order")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booking_slots")),
        sa.UniqueConstraint("start_time", name=op.f("uq_booking_slots_start_time")),
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("phone", name=op.f("uq_customers_phone")),
    )
    op.create_table(
        "dining_tables",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("min_capacity", sa.SmallInteger(), nullable=False),
        sa.Column("max_capacity", sa.SmallInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "min_capacity <= max_capacity", name=op.f("ck_dining_tables_capacity_range")
        ),
        sa.CheckConstraint(
            "min_capacity >= 1", name=op.f("ck_dining_tables_min_capacity_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dining_tables")),
        sa.UniqueConstraint("name", name=op.f("uq_dining_tables_name")),
    )
    op.create_table(
        "reservations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("table_id", sa.Integer(), nullable=False),
        sa.Column("booking_slot_id", sa.Integer(), nullable=False),
        sa.Column("reservation_date", sa.Date(), nullable=False),
        sa.Column("party_size", sa.SmallInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "confirmed", "cancelled", name="reservationstatus", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('confirmed', 'cancelled')", name=op.f("ck_reservations_status")
        ),
        sa.CheckConstraint("party_size BETWEEN 1 AND 8", name=op.f("ck_reservations_party_size")),
        sa.ForeignKeyConstraint(
            ["booking_slot_id"],
            ["booking_slots.id"],
            name=op.f("fk_reservations_booking_slot_id_booking_slots"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_reservations_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["table_id"], ["dining_tables.id"], name=op.f("fk_reservations_table_id_dining_tables")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservations")),
    )
    op.create_index(
        op.f("ix_reservations_customer_id"), "reservations", ["customer_id"], unique=False
    )
    op.create_index(
        "ix_reservations_date_slot",
        "reservations",
        ["reservation_date", "booking_slot_id"],
        unique=False,
    )
    op.create_index(
        "uq_reservations_table_date_slot_confirmed",
        "reservations",
        ["table_id", "reservation_date", "booking_slot_id"],
        unique=True,
        postgresql_where=sa.text("status = 'confirmed'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_reservations_table_date_slot_confirmed",
        table_name="reservations",
        postgresql_where=sa.text("status = 'confirmed'"),
    )
    op.drop_index("ix_reservations_date_slot", table_name="reservations")
    op.drop_index(op.f("ix_reservations_customer_id"), table_name="reservations")
    op.drop_table("reservations")
    op.drop_table("dining_tables")
    op.drop_table("customers")
    op.drop_table("booking_slots")
    # ### end Alembic commands ###
